name: Deploy VitePress site and Marp slides to Pages

on:
  push:
    branches: [main]
    paths:
        - 'slides/**'
        - 'src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # or pnpm / yarn
      - name: Setup Pages
        uses: actions/configure-pages@v4
      # VitePress
      - name: Install dependencies
        run: npm ci 
      - name: Build with VitePress
        run: npm run build # or pnpm docs:build / yarn docs:build / bun run docs:build
      # Marp
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli
      - name: Generate PDF and HTML
        run: |
          mkdir -p public/slides
          for file in slides/*.md; do
            marp "$file" --pdf --output "public/slides/$(basename "${file%.md}.pdf")"
            marp "$file" --html --output "public/slides/$(basename "${file%.md}.html")"
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
